---
- hosts: webservers
  become: yes
  tasks:
    - name: INSTALL APACHE2
      apt: name=apache2 update_cache=yes state=latest

    - name: ENABLED MOD_REWRITE
      apache2_module: name=rewrite state=present
      notify:
        - RESTART APACHE2

    - name: APACHE2 LISTEN ON PORT 8081
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
      notify:
        - RESTART APACHE2

    - name: APACHE2 VIRTUALHOST ON PORT 8081
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8081>" state=present
      notify:
        - RESTART APACHE2

    - name: MARK /var/www/html AS A SAFE DIRECTORY
      ansible.builtin.command:
        cmd: git config --global --add safe.directory /var/www/html

    - name: DEPLOY JD SPORTS WEBSITE FILES
      ansible.builtin.git:
        repo: 'https://github.com/Munasar151/JD-Sports.git'
        dest: '/var/www/html/'
        version: 'main'
        force: 'yes'
        

  handlers:
    - name: RESTART APACHE2
      service: name=apache2 state=restarted
